apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-tasks
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
      - name: taskpersistence
        image: redis:5
        args: ["redis-server", "/redis/redis.conf"]
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "sleep 10"]
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /var/log
          name: logs-endpoint
        - mountPath: /data
          name: data-endpoint
        - mountPath: /redis
          name: redis-config
      - name: tasks
        image: "{{ .Values.registry }}/tasks:{{ .Values.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 5003
        envFrom:
        - configMapRef:
            name: common-env-file
        - configMapRef:
            name: tasks-env-file
        volumeMounts:
        - mountPath: /var/log
          name: logs-endpoint
        - mountPath: /f7t-ssl.crt
          name: f7t-ssl-crt
          subPath: f7t-ssl.crt
        - mountPath: /f7t-ssl.key
          name: f7t-ssl-key
          subPath: f7t-ssl.key
        startupProbe:
          tcpSocket:
            port: 5003
          initialDelaySeconds: 5
          failureThreshold: 1
      {{ if .Values.registry_secret_creds }}
      imagePullSecrets:
      - name: "{{ .Values.registry_secret_creds }}"
      {{ end }}
      volumes:
      - name: logs-endpoint
        emptyDir: {}
      - name: data-endpoint
        emptyDir: {}
      - name: redis-config
        configMap:
          name: f7t-redis
      - name: f7t-ssl-crt
        configMap:
          name: f7t-ssl-crt
      - name: f7t-ssl-key
        configMap:
          name: f7t-ssl-key
