apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-storage
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage
  template:
    metadata:
      labels:
        app: storage
    spec:
      containers:
      - image: "{{ .Values.registry }}/storage:{{ .Values.tag }}"
        imagePullPolicy: Always
        name: storage
        ports:
        - containerPort: 5002
        envFrom:
        - configMapRef:
            name: common-env-file
        - configMapRef:
            name: storage-env-file
        volumeMounts:
        - mountPath: /var/log
          name: logs-endpoint
        - mountPath: /user-key
          subPath: user-key
          name: user-key-public
        startupProbe:
          tcpSocket:
            port: 5002
          initialDelaySeconds: 5
          failureThreshold: 1
      {{ if .Values.registry_secret_creds }}
      imagePullSecrets:
      - name: "{{ .Values.registry_secret_creds }}"
      {{ end }}
      volumes:
      - emptyDir: {}
        name: logs-endpoint
      - name: user-key-public
        configMap:
          name: f7t-user-ssh-keys